import type { Metadata } from "next";
import { Section, SectionHeading } from "@/components/marketing/section";

export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <Section border={false} className="pb-24">
      <SectionHeading eyebrow="Legal" title="Privacy Policy" center={false} />
      <div className="mx-auto mt-10 max-w-2xl space-y-6 text-sm leading-relaxed text-muted-foreground">
        <p className="rounded-lg border border-border bg-card p-4 text-foreground/90">
          Placeholder policy for demo purposes. Have counsel review and finalize this before
          collecting real customer data.
        </p>
        <div>
          <h2 className="text-base font-semibold text-foreground">What we collect</h2>
          <p className="mt-2">
            Contact details you submit through our forms (name, email, company, message),
            campaign performance data (visits, clicks, leads) generated by landing pages we build
            for you, and standard analytics data (device, approximate location, referrer) via
            PostHog.
          </p>
        </div>
        <div>
          <h2 className="text-base font-semibold text-foreground">How we use it</h2>
          <p className="mt-2">
            To run and report on the engagement you&apos;ve hired us for, to respond to inquiries, and
            to improve our own landing pages and process. We do not sell personal data to third
            parties.
          </p>
        </div>
        <div>
          <h2 className="text-base font-semibold text-foreground">Payment data</h2>
          <p className="mt-2">
            Payments are processed by Stripe. We never see or store full card numbers — Stripe
            handles that under its own PCI-compliant infrastructure.
          </p>
        </div>
        <div>
          <h2 className="text-base font-semibold text-foreground">Your rights</h2>
          <p className="mt-2">
            You can request a copy of, correction to, or deletion of your data at any time by
            contacting us. Leads and campaign data collected on your behalf are yours — we export
            them to you on request or at project close.
          </p>
        </div>
        <div>
          <h2 className="text-base font-semibold text-foreground">Contact</h2>
          <p className="mt-2">Questions about this policy: reach us via the contact page.</p>
        </div>
      </div>
    </Section>
  );
}
