<?php

declare(strict_types=1);

namespace KPI\Checkout;

use PDO;
use PDOException;
use Throwable;

/**
 * Writes paid orders into the same database Prisma owns.
 *
 * The checkout does not run migrations and does not define its own schema — it
 * writes User and Order rows exactly as prisma/schema.prisma declares them, so
 * a purchase taken here shows up in the Next.js client dashboard with no sync
 * step. Two details of Prisma's SQLite mapping matter and are easy to get
 * wrong: DateTime columns hold integer milliseconds (not SQL datetime text),
 * and ids are cuid strings generated by the client, not autoincrement.
 *
 * Recording is best-effort by design. A database that is unreachable, on
 * Postgres, or mid-migration must never turn a successful charge into an error
 * page for the buyer — the webhook retries, and Stripe remains the ledger of
 * record either way.
 */
final class Orders
{
    private static int $counter = 0;

    private function __construct(private readonly PDO $pdo)
    {
    }

    /**
     * Open the Prisma SQLite file named by DATABASE_URL.
     *
     * Returns null (with a log line) for anything this writer cannot handle,
     * including a Postgres URL — production is expected to point DATABASE_URL
     * at Postgres, where the Next.js webhook owns order recording instead.
     */
    public static function open(?string $databaseUrl, string $projectRoot): ?self
    {
        if ($databaseUrl === null || $databaseUrl === '') {
            return null;
        }

        if (!str_starts_with($databaseUrl, 'file:')) {
            error_log('[checkout] DATABASE_URL is not a SQLite file: URL — skipping local order recording.');

            return null;
        }

        $path = substr($databaseUrl, 5);

        // Prisma resolves relative SQLite paths against the schema directory.
        if (!str_starts_with($path, '/')) {
            $path = $projectRoot . '/prisma/' . ltrim($path, './');
        }

        if (!is_file($path) || !is_writable($path)) {
            error_log(sprintf('[checkout] SQLite database %s is missing or not writable — skipping local order recording.', $path));

            return null;
        }

        try {
            $pdo = new PDO('sqlite:' . $path, null, null, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_TIMEOUT => 5,
            ]);
            $pdo->exec('PRAGMA foreign_keys = ON');
        } catch (PDOException $e) {
            error_log('[checkout] Could not open the SQLite database: ' . $e->getMessage());

            return null;
        }

        return new self($pdo);
    }

    /**
     * Record a paid order, idempotently.
     *
     * Called from both the return page and the webhook — whichever arrives
     * first wins, the other one is a no-op. BEGIN IMMEDIATE takes the write
     * lock up front so the two cannot interleave into a duplicate row: SQLite
     * has no upsert target here, because Prisma's unique index is on
     * stripeSessionId (a hosted Checkout concept this flow never creates).
     *
     * @param array<string,mixed> $package
     * @return array{created:bool, orderId:?string}
     */
    public function recordPaid(
        array $package,
        string $email,
        ?string $name,
        int $amountCents,
        string $currency,
        string $paymentIntentId,
    ): array {
        try {
            $this->pdo->exec('BEGIN IMMEDIATE');

            $existing = $this->pdo->prepare('SELECT "id", "status" FROM "Order" WHERE "stripePaymentIntentId" = ? LIMIT 1');
            $existing->execute([$paymentIntentId]);
            $order = $existing->fetch();

            if ($order !== false) {
                if (($order['status'] ?? null) !== 'PAID') {
                    $update = $this->pdo->prepare('UPDATE "Order" SET "status" = ? WHERE "id" = ?');
                    $update->execute(['PAID', $order['id']]);
                }

                $this->pdo->exec('COMMIT');

                return ['created' => false, 'orderId' => (string) $order['id']];
            }

            $userId = $this->upsertUser($email, $name);
            $orderId = self::cuid();

            $insert = $this->pdo->prepare(
                'INSERT INTO "Order" ("id", "userId", "package", "amountCents", "currency", "stripeSessionId", "stripePaymentIntentId", "status", "createdAt")
                 VALUES (?, ?, ?, ?, ?, NULL, ?, ?, ?)'
            );
            $insert->execute([
                $orderId,
                $userId,
                (string) $package['dbType'],
                $amountCents,
                strtolower($currency),
                $paymentIntentId,
                'PAID',
                self::nowMs(),
            ]);

            $this->pdo->exec('COMMIT');

            return ['created' => true, 'orderId' => $orderId];
        } catch (Throwable $e) {
            try {
                $this->pdo->exec('ROLLBACK');
            } catch (Throwable) {
                // Nothing useful to do; the original failure is what matters.
            }

            error_log('[checkout] Could not record the order locally: ' . $e->getMessage());

            return ['created' => false, 'orderId' => null];
        }
    }

    /** Find the buyer by email or create them, matching the webhook's upsert. */
    private function upsertUser(string $email, ?string $name): string
    {
        $email = strtolower(trim($email));

        $lookup = $this->pdo->prepare('SELECT "id" FROM "User" WHERE "email" = ? LIMIT 1');
        $lookup->execute([$email]);
        $found = $lookup->fetch();

        if ($found !== false) {
            return (string) $found['id'];
        }

        $userId = self::cuid();
        $displayName = $name !== null && trim($name) !== ''
            ? trim($name)
            : (explode('@', $email)[0] ?: $email);

        $insert = $this->pdo->prepare(
            'INSERT INTO "User" ("id", "email", "name", "role", "company", "createdAt") VALUES (?, ?, ?, ?, NULL, ?)'
        );
        $insert->execute([$userId, $email, $displayName, 'CLIENT', self::nowMs()]);

        return $userId;
    }

    /** Prisma stores SQLite DateTime as integer milliseconds since the epoch. */
    private static function nowMs(): int
    {
        return (int) round(microtime(true) * 1000);
    }

    /**
     * A cuid-shaped id: 'c' + base36 time + counter + fingerprint + entropy.
     *
     * Prisma generates these client-side, so PHP has to produce ids in the same
     * shape for rows written outside Prisma to look native in the dashboard.
     */
    public static function cuid(): string
    {
        $time = base_convert((string) self::nowMs(), 10, 36);
        $counter = str_pad(base_convert((string) (self::$counter++ % 1_679_616), 10, 36), 4, '0', STR_PAD_LEFT);
        $fingerprint = substr(md5((gethostname() ?: 'kpi') . (string) getmypid()), 0, 4);
        $entropy = substr(bin2hex(random_bytes(6)), 0, 8);

        return 'c' . $time . $counter . $fingerprint . $entropy;
    }
}
